app/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from app import views

urlpatterns = patterns('',
    url(r'^index$', views.index, name='home'),
    url(r'^approve_single$', views.approve_single, name='ffamily_approve_single'),
    url(r'^approve_all$', views.approve_all, name='ffamily_approve_all'),
    url(r'^unapprove_all$', views.unapprove_all, name='ffamily_disapprove_all'),
    url(r'^font_correction$', views.font_correction, name='font_correction'),
    url(r'^font_non_tk_correction$', views.font_non_tk_correction, name='font_non_tk_correction'),
)

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

font_classificator/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, url, include

from app import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index),
    url(r'', include('app.urls'))
]

app/models.py
from django.db import models
from django.db.models import Max
from django.db.models import Q

# the 8 special typekit classes + other classes
class FontClass(models.Model):
    name = models.CharField(max_length=64)
    is_original = models.BooleanField() 

    def is_typekit_class(self):
        return self.name.istartswith('tk_')

    def __str__(self):
        return "{}, is_original: {}".format(self.name, self.is_original)

class FontFamily(models.Model):
    prediction_threshold = 0.5

    name = models.CharField(max_length=64)
    url = models.URLField(null=True)
    is_approved = models.BooleanField(default=False)
    is_typekit_family = models.BooleanField() # does it come from typekit.com?
    is_whitelisted = models.BooleanField(default=False)
    font_classes = models.ManyToManyField(FontClass) # the 8 special typekit classes + other classes
    
    def is_font_class_predicted(self, font_class=None):
        pr_val = self.font_class_predicted_value(font_class)
        return pr_val > self.prediction_threshold
   
    def font_class_predicted_value(self, font_class_name=None):
        fpred = FontPrediction.objects.filter(font_face__font_family=self)
        if font_class_name != None:
            fpred = fpred.filter(font_class__name=font_class_name)
        
        return fpred.aggregate(Max('value'))['value__max']

    def font_typekit_class(self):
        return self.font_classes.all().filter(is_original=True, name__startswith='tk_', fontclassvalue__value=1, fontclassvalue__font_family=self).first()

    def font_other_classes(self):
        fc_list = self.font_classes.all().filter(is_original=True, fontclassvalue__value=1, fontclassvalue__font_family=self)
        return filter(lambda x: not x.name.startswith('tk_'), fc_list)

    def font_class_correction(self):
        return self.font_classes.all().filter(is_original=False, fontclassvalue__value=1, fontclassvalue__font_family=self).first()

    def set_new_tk_font_class_correction(self, new_font_class_id):
        # reset all values to 0
        fcv_list = FontClassValue.objects.all().filter(font_class__name__startswith='tk_', font_class__is_original=False, font_family=self)
        if fcv_list:
            fcv_list.update(value=0)

        # set the new value to 1
        if int(new_font_class_id) != 0:
            new_font_class = FontClass.objects.get(id=new_font_class_id)
            fcv = FontClassValue.objects.all().filter(font_class=new_font_class, font_family=self).first()
            if fcv:
                fcv.value = 1
            else:
                fcv = FontClassValue(font_class=new_font_class, font_family=self, value=1)
                self.font_classes.add(new_font_class)
                self.save()   
            
            fcv.save()
        else:
            raise ValueError('new_font_class_id has to have the value > 0')

    def get_font_class_non_tk_correction_status(self, non_tk_class):
        if not non_tk_class.name.startswith('b_'):
            raise ValueError('The name of non_tk_class_name has to start with b_')

        fc = FontClass.objects.get(name=non_tk_class.name)
        fcv = FontClassValue.objects.all().filter(font_class__is_original=True, font_class=fc, font_family=self).first()
        # fcv = FontClassValue.objects.all().filter(font_class=fc, font_family=self).first()
        return -1 if fcv is None or fcv.value is None else fcv.value

    def set_non_tk_font_class_correction(self, font_class_name, value):
        fc = FontClass.objects.get(name=font_class_name)
        fcv = FontClassValue.objects.all().filter(font_class=fc, font_family=self).first()
        if fcv:
            fcv.value = value
        else:
            fcv = FontClassValue(font_class=fc, font_family=self, value=value)
            self.font_classes.add(fc)
            self.save()   
            
        fcv.save()

#    def is_whitelisted(self):
#        return FontFamily.objects.filter(font_family=self).first()

    def __str__(self):
        return self.name

class FontClassValue(models.Model):
    value = models.IntegerField(default=None, null=True, blank=True)
    font_class = models.ForeignKey(FontClass)
    font_family = models.ForeignKey(FontFamily)
    
    def __str__(self):
        return "{}, {}, ({}, {})".format(self.id, self.value, self.font_class.name, self.font_family.name)

class FontFace(models.Model):
    name = models.CharField(max_length=64)
    font_family = models.ForeignKey(FontFamily)
    is_sortable = models.BooleanField(default=False, blank=True) 

    def __str__(self):
        return self.name

class FontPrediction(models.Model):
    font_face = models.ForeignKey(FontFace) #todo OneToOneField(FontFace)
    font_class = models.ForeignKey(FontClass)
    value = models.FloatField()

    def __str__(self):
        return str(self.value)



# import pdb; pdb.set_trace()

app/templates/base.html
<!doctype html>
{% load static %}
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Font classficator</title>
    <!-- <script src="{% static 'js/script01.js' %}" type="text/css" />
    <script src="{% static 'js/jquery-2.1.4.min.js' %}" type="text/css" /> -->
    <link rel="stylesheet" href="{% static 'css/style01.css' %}" type="text/css" />
    {% block head_block %}{% endblock %}
    </head>
<body>
    <div id="container">
    {% block body_block %}{% endblock %}
    <footer>
        <div class="footer-content width">
            <div class="clear"></div>
        </div>
        <div class="footer-bottom">
            <p>&copy; Font classificator 2015.</p>
         </div>
    </footer>
</div>
</body>
</html>

app/templates/index.html
<!doctype html>
{% load static from staticfiles %}

<html>
  <head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Font classification viewer</title>
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/jquery-editable-poshytip.min.js' %}"></script>
    <script src="{% static 'js/script01.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/jquery-editable.css' %}" type="text/css" />
  </head>
  <body>
    <style>
      ul{
          list-style: none;
          border-top: 1px solid #221F1F;
      }
     
      li {
          display: inline-block;
          width: 23%;
      }

      ul li img{
        display:block;
      }

      .filter-label {
        padding-left: 25px; 
      }

      .font_family_item {
        border: 1px solid black;
        margin: 15px;
        padding: 10px;
      }
  </style>
  <script type="text/javascript">
    var fontClasses = {{ font_classes_js|safe }};
  </script>
    
    <h1 align='center'><a href='/'>Font Classification Viewer</a></h1>
    <div style="margin: 15px; border: solid 1px black; padding: 10px">
      <label for='ddl_font_class'>Class</label>
      <select id='ddl_font_class' name='ddl_font_class'>
          <option value='0'>All</option>
          <option value='1'>No TK class</option>
          {% for x in font_classes %}
            <option value='{{x.name}}' {% if font_class and font_class.name == x.name %} selected='selected' {% endif %}>{{x.name}}(debug, id: {{x.id}})</option>
          {% endfor %}
      </select>

      <label for='chk_positive' class="filter-label">Positive</label>
      <input type='checkbox' {% if positive == True or positive == None %} checked='checked' {% endif %} name='chk_positive' id='chk_positive'/>
      
      <label for='chk_predicted' class="filter-label">Predicted</label>
      <input type='checkbox' name='chk_predicted' id='chk_predicted' {% if predicted %} checked='checked' {% endif %} />

      <label for='chk_corrected' class="filter-label">Corrected</label>
      <input type='checkbox' name='chk_corrected' id='chk_corrected' {% if corrected %} checked='checked' {% endif %} />
      
      <label for='chk_unapproved_only' class="filter-label">Unapproved only</label>
      <input type='checkbox' name='chk_unapproved_only' id='chk_unapproved_only' {% if unapproved_only %} checked='checked' {% endif %}  />

      <label for='chk_whitelist_only' class="filter-label">Whitelist only</label>
      <input type='checkbox' name='chk_whitelist_only' id='chk_whitelist_only' {% if whitelist_only %} checked='checked' {% endif %}  />

      <br />
      <br />
      <p>
        <label for='ddl_sort_by'>Sort by</label>
        <select id='ddl_sort_by' class='ddl_sort_by' data-ffamily-id='{{ffamily.id}}'>
          <option value='0'>Alphabetical</option>
          {% for x in font_classes %}
            <option value='{{x.name}}' {% if sort_by.id == x.id %} selected='selected' {% endif %}>{{x.name}}</option>
          {% endfor %}
        </select>

        <label for='chk_prediction' class="filter-label">Prediction</label>
        <input type='checkbox' {% if prediction_sort %} checked='checked' {% endif %} name='chk_prediction' id='chk_prediction' />
        <label for='chk_decreasing' class="filter-label">Decreasing</label>
        <input type='checkbox' {% if descreasing_sort %} checked='checked' {% endif %} name='chk_decreasing' id='chk_decreasing' />
      
      </p>
      {% if sort_by.id != '0' %}
      Predictions {% if allow_non_tk_correction %} and corrections for non tk classes {% endif %} are shown for sort by <b>{{sort_by.name}}</b>
      {% endif %}
      
      {% if enable_editing %}
        <p>
          <button name='btn_approve_all' id='btn_approve_all'>Approve all</button>
          <button name='btn_unapprove_all' id='btn_unapprove_all'>Unapprove all</button>
        </p>
      {% endif %}
    </div>


    <div class="pagination">
      <span class="step-links">
          {% if data.has_previous %}
              <a href="?page={{ data.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">previous</a>
          {% endif %}

          <span class="current">
              <b>Page</b> {{ data.number }} of {{ data.paginator.num_pages }}
          </span>

          {% if data.has_next %}
              <a href="?page={{ data.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">next</a>
          {% endif %}

      </span>
    </div>

    
    <div id='font_families'>
      {% for ffamily in data %}
        <div class='font_family_item'>
          <table>
            <tr>
              <td>
                <h3>
                  {% if ffamily.url %}
                    <a href='{{ffamily.url}}'>{{ffamily}}</a>
                  {% else %}
                    {{ffamily}}  
                  {% endif %}
                  {% if ffamily.is_typekit_family %}
                    (TK)
                  {% endif %}
                  ({{ffamily.id}})
                  {% if enable_editing %}
                    <span>
                      <button class='btn_approve_font_family' data-ffamily-id='{{ffamily.id}}'>Approve</button>
                    </span>
                  {% endif %}
                </h3>

                <b>Typekit&nbsp;Class:</b>&nbsp;{{ffamily|font_typekit_class}}
                <br />

                <b>Other&nbsp;classes:</b>
                {% if ffamily|font_other_classes %}
                  {{ffamily|font_other_classes}}
                {% endif %}
                <br/>
                
                <b>Whitelist:</b>
                {{ffamily|ffamily_is_whitelisted}}
                <br/>
                
                <b>Correction (TK):</b>
                {% if enable_editing %}
                  <select id='ddl_font_correction_{{ffamily.id}}' class='ddl_font_correction' data-ffamily-id='{{ffamily.id}}'>
                    <option value='0'>None</option>
                    {% for x in font_classes_corrected %}
                      <option value='{{x.id}}' {% if x.id == ffamily|ffamily_correction_id %} selected='selected' {% endif %}>{{x.name}}</option>
                    {% endfor %}
                  </select>
                {% else %}
                  {{ffamily|ffamily_correction_name}}
                {% endif %}


                {% if allow_non_tk_correction %}
                  <br />
                  <b>Correction (non TK):</b>
                  {% if enable_editing %}
                    <select id='ddl_font_non_tk_correction_{{ffamily.id}}' class='ddl_font_non_tk_correction' data-ffamily-id='{{ffamily.id}}'>

                      {% get_font_class_non_tk_correction_status ffamily.id sort_by.id as fc_non_tk_corr_value %}
                      {% for x in non_tk_correction_values %}

                        <option value='{{x}}' {% if x == fc_non_tk_corr_value %} selected='selected' {% endif %}>{{x}}</option>
                      {% endfor %}
                    </select>
                  {% else %}
                    {{ fc_non_tk_corr_value }}
                  {% endif %}
                {% endif %}
                
                
                {% if sort_by.id != '0' %}
                <br />
                <b>Prediction:</b> {{ffamily|ffamily_font_class_predicted_value_by_class:sort_by.id|safe}} 
                {% endif %}
          </td>

            {% for fface in ffamily.fontface_set.all %}
              <td><center>
                <img src='/static/img/{{fface}}.png' style='width: 300px; height: 120px' /><br>
                <b>{{fface}}</b>
                </center>
              </td>
            {% endfor %}
</tr>
</table>
        </div>

      {% endfor %}
    </div>

    <div class="pagination">
      <span class="step-links">
          {% if data.has_previous %}
              <a href="?page={{ data.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">previous</a>
          {% endif %}

          <span class="current">
              <b>Page</b> {{ data.number }} of {{ data.paginator.num_pages }}
          </span>

          {% if data.has_next %}
              <a href="?page={{ data.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">next</a>

          {% endif %}

      </span>
    </div>
  </body>
</html>